PSI/psi_p4/labassign/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('convalidation/', views.convalidation, name='convalidation'),
    path('applypair/', views.applypair, name='applypair'),
    path('breakpair/', views.breakpair, name='breakpair'),
    path('applygroup/', views.applygroup, name='applygroup'),
]

PSI/psi_p4/labassign/labassign/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
]

PSI/psi_p4/labassign/core/forms.py
from django import forms
from core.models import GroupConstraints, Pair, Student
from django.contrib.auth.models import User
from django.db.models import Q


class BreakPairForm(forms.Form):
    # creation of the pulldown menu
    myPair = forms.ModelChoiceField(
        queryset=None, label="Select the pair to be broken")

    def __init__(self, user, listID, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        # filter all the Pairs you are interested
        # all the ones where the user is in
        pair = Pair.objects.filter(student1=user).values_list('student1', flat=True)
        # convert to a list
        pair = [entry for entry in pair]
        # put it in to a list
        listID = listID.union(set(pair))

        # filter all the Pairs you are interested
        # all the ones where the user is in
        pair = Pair.objects.filter(student2=user).values_list('student2', flat=True)
        # convert to a list
        pair = [entry for entry in pair]
        # put it in to a list
        listID = listID.union(set(pair))

        # get all the pairs that exist in the database
        # even they are not validated
        self.fields['myPair'].queryset = Pair.objects.all().filter(Q(student1__in=listID) | Q(student2__in=listID))


# class from for the lab group formation
class GroupForm(forms.Form):
    # creation of the pulldown menu
    myLabGroup = forms.ModelChoiceField(
        queryset=None, label="Select the group you want to join to")

    def __init__(self, user, listID, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        # filter all the groups you are interested in
        # you want the ones that have the group constraints
        # theory group the same
        groupsCant = GroupConstraints.\
            objects.filter(theoryGroup=user.theoryGroup)\
            .values_list('theoryGroup', flat=True)
        # convert to a list
        groupsCant = [entry for entry in groupsCant]
        # put it in to a list
        listID = listID.union(set(groupsCant))
        # put in the pulldown menu the lab groups you got in
        # the prevoious cases
        self.fields['myLabGroup'].queryset = GroupConstraints\
            .objects.filter(theoryGroup__in=listID)


# class from for the pair formation
class PairForm(forms.Form):
    # creation of the pulldown menu
    secondMemberGroup = forms.ModelChoiceField(queryset=None,
                                               label="Select the second"
                                                     " member of the pair")

    def __init__(self, user, listID, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        # filter all the groups you are not interested in
        # you don not want yourself to be in a pair with
        listID.add(user)

        # you do not want someone that already have a pair
        pairValidated1 = Pair.objects.filter(validated=True).\
            values_list('student1', flat=True)
        # convert to a list
        pairValidated1 = [entry for entry in pairValidated1]
        # put it in to a list
        listID = listID.union(set(pairValidated1))

        # you do not want someone that already have a pair
        pairValidated2 = Pair.objects.filter(validated=True).\
            values_list('student2', flat=True)
        # convert to a list
        pairValidated2 = [entry for entry in pairValidated2]
        # put it in to a list
        listID = listID.union(set(pairValidated2))

        # eclude from the pulldown menu the students you got in
        # the prevoious cases
        self.fields['secondMemberGroup'].queryset = Student.\
            objects.all().exclude(id__in=listID)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

PSI/psi_p4/labassign/core/views.py
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from core.models import LabGroup, Pair, OtherConstraints, Student
from core.forms import PairForm, GroupForm, BreakPairForm
from django.db.models import Q

# view for the home page
def home(request):
    # get the user that is logged in in this moment
    user = request.user
    # create a dictionary that will help us ih the html
    # when showing messages
    context_dict = {}
    # search if the user is the first member of a pair.
    # we will need this to show the name of the pair
    # in the html
    try:
        pairs = Pair.objects.filter(student1_id=user.id).first()
    except pairs.doesNotExist:
        context_dict = {}

    # search if the user is the second member of a pair.
    # we will need this to show the name of the pair
    # in the html
    try:
        pairs2 = Pair.objects.filter(student2_id=user.id,
                                     validated=True).first()
        # puts the pair where the user is in in the dictionary
        context_dict = {'pairs': pairs, 'pairs2': pairs2}
    except pairs.doesNotExist:
        context_dict = {}
    # returns the dictionary to the home page
    return render(request, 'core/home.html', context=context_dict)


# view for the applygroup page
def applygroup(request):
    # get the user that is logged in in this moment
    user = request.user
    # create a dictionary that will help us ih the html
    # when showing messages
    context_dict = {}
    # create a set to send it to the forms.py
    listID = set()
    # variable for the constrains we will need
    cons = OtherConstraints.objects.get(id=1)
    # variable for our time
    dt = timezone.now()
    # we put the variables already created in the dictionary
    context_dict = {'cons': cons, 'dt': dt}
    # if the user is authenticated
    if request.user.is_authenticated:
        # if the user has used the dropdown menu:
        if request.method == 'POST':
            # gets the answer of the user
            form = GroupForm(user, listID, request.POST)
            if form.is_valid():
                # if it is correct it will take the id of the lab
                # the user wants to join to
                labGroupID = form['myLabGroup'].value()
                # it gets the lab from the id to have all the other
                # variables
                lab = LabGroup.objects.get(id=labGroupID)
                if cons.selectGroupStartDate <= dt:
                    pair = Pair.objects.filter((Q(student1=user)
                                                | Q(student2=user)),
                                               Q(validated=True)).first()
                    # if the date is allowed and the user is not in a pair,
                    # the program add him to the lab group if it has not
                    # achieved the maxNumberOfStudents the lab can get
                    # after adding him to the lab, it updates the lab counter
                    if not pair:
                        if lab.counter < lab.maxNumberStudents:
                            Student.objects.filter(id=user.id). \
                                update(labGroup=labGroupID)
                            LabGroup.objects.filter(id=labGroupID). \
                                update(counter=lab.counter + 1)
                    # if the date is allowed but the user IS in a pair,
                    # the program add him to the lab group he asked for
                    # as well as the partner he has, but if
                    # the lab group has not achieved the maxNumberOfStudents
                    # the lab can get
                    # after adding him and his partner to the lab, it updates
                    # the lab counter by 2
                    else:
                        if lab.counter <= lab.maxNumberStudents - 1:
                            Student.objects.filter(id=pair.student1.id). \
                                update(labGroup=labGroupID)
                            Student.objects.filter(id=pair.student2.id). \
                                update(labGroup=labGroupID)
                            LabGroup.objects.filter(id=labGroupID). \
                                update(counter=lab.counter + 2)
        # show the dropdown menu
        else:
            form = GroupForm(user, listID)
            context_dict["form"] = form
        # return the dict (with the variables we will need and the menu)
        # to the applygroup page
        return render(request, 'core/applygroup.html', context_dict)
    # if the user is not authenticated it will redirect him to the
    # login page
    else:
        return render(request, 'core/login.html')


# view for the breakpair page
def breakpair(request):
    user = request.user
    listID = set()
    context_dict = {}
    # if the user is authenticated
    if user.is_authenticated:
        # if the user has used the dropdown menu:
        if request.method == 'POST':
            # gets the answer of the user
            form = BreakPairForm(user, listID, request.POST)
            if form.is_valid():
                # if it is correct it will take
                # the id of the pair
                pair = form['myPair'].value()
                # it gets the logged user
                stud = Student.objects.get(id=request.user.id)
                # get the student2 id
                stud2 = None
                if Pair.objects.filter(id=pair, student1=stud).exists():
                    stud2 = Pair.objects.get(id=pair, student1=stud).student2
                elif Pair.objects.filter(id=pair, student2=stud).exists():
                    stud2 = Pair.objects.get(id=pair, student2=stud).student1
                if not stud2:
                    context_dict = {'error': stud2}
                    return render(request, 'core/breakpair.html', context=context_dict)
                # the logged user is the one that ask
                # breaking the pair
                # if Pair.objects.filter(id=pair, student1=stud, student2=stud2).exists() or \
                #        Pair.objects.filter(id=pair, student1=stud2, student2=stud).exists():

                # if the user and his pair are not already in a group
                if Student.objects.filter(id=stud.id, labGroup=None).exists() and \
                        Student.objects.filter(id=stud2.id, labGroup=None).exists():
                    # if the pair is not validated
                    if Pair.objects.filter(id=pair, validated=False).exists():
                        # deletes the pair
                        Pair.objects.filter(id=pair, validated=False).delete()
                    # if the pair is validated
                    elif Pair.objects.filter(id=pair, validated=True).exists():
                        # if there is not a request for breaking the pair yet
                        if Pair.objects.filter(id=pair, validated=True,
                                               studentBreakRequest=None).exists():
                            p = Pair.objects.get(id=pair, validated=True,
                                                 studentBreakRequest=None)
                            p.studentBreakRequest = stud
                            p.save()
                        # if there is a request for breaking the pair already
                        else:
                            # deletes the pair
                            Pair.objects.filter(id=pair, validated=True).delete()
        # show the dropdown menu
        else:
            context_dict = {'error': user}
            form = BreakPairForm(user, listID)
            context_dict["form"] = form
        # return the dict (with the variables we will need and the menu)
        # to the breakpair page
        return render(request, 'core/breakpair.html', context=context_dict)
    # if the user is not authenticated it will redirect him to the
    # login page
    else:
        return render(request, 'core/login.html')


# view for the applypair page
def applypair(request):
    # get the user that is logged in in this moment
    user = request.user.id
    selectedPair = False
    # create a dictionary that will help us ih the html
    # when showing messages
    context_dict = {}
    listID = set()
    # if the user is authenticated
    if request.user.is_authenticated:
        # if the user has used the dropdown menu:
        if request.method == 'POST':
            # gets the answer of the user
            form = PairForm(user, listID, request.POST)
            if form.is_valid():
                # if it is correct it will take the id of the
                # new pair that is created
                secondMemberID = form['secondMemberGroup'].value()
                # it gets the logged user
                stud = Student.objects.get(id=request.user.id)
                # it gets the partner the logged user selected in the menu
                stud2 = Student.objects.get(id=secondMemberID)
                if Pair.objects.filter(student1=stud2, student2=stud).exists():
                    # if the pair of the student1 = stud2 and
                    # student2 = stud exists,
                    # it means it was already created so it set the validated
                    # field to True
                    pair = Pair.objects.get(student1=stud2, student2=stud)
                    pair.validated = True
                    # if the stud2 has a labgroup, it will be the same as the
                    # stud.
                    stud.labGroup = stud2.labGroup
                    stud.save()
                    pair.save()
                else:
                    # if the pair of the student1 = stud2 and

PSI/psi_p4/labassign/templates/core/applygroup.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Apply Group
{% endblock %}

{% block body_block %}
	{% if cons.selectGroupStartDate <= dt %}
		<form method="post" action="{% url 'core:applygroup' %}">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Submit" name="groupSel">
		</form>
	{% else %}
		Group selection is not active
	{% endif %}


{% endblock %}

PSI/psi_p4/labassign/templates/core/applypair.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Apply Pair
{% endblock %}

{% block body_block %}
	<form method="post" action="{% url 'core:applypair' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" name="student2">
	</form>

	{% if form.errors %}
      {% for field in form %}

           {% for error in field.errors %}
               Could not process your request
           {% endfor %}

      {% endfor %}
    {% endif %}

    {% if selectedPair == True %}
        User has already selected a pair
    {% endif %}

{% endblock %}

PSI/psi_p4/labassign/templates/core/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}

<html lang="en">
    <head>
        <title>
            {% block title_block %}
            {% endblock %}
        </title>
        <link rel="stylesheet" href="{% static 'core/style.css' %}">
    </head>
    <body class="text">
        <div class="index">
            <ul>
                <li><a href="{% url 'core:home' %}">Home</a></li>
                <li><a href="{% url 'core:login' %}">Log-In</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'core:logout' %}">Log-Out</a></li>
                <li><a href="{% url 'core:convalidation' %}">Convalidation</a></li>
                <li><a href="{% url 'core:applypair' %}">Apply Pair</a></li>
                <li><a href="{% url 'core:breakpair' %}">Break Pair</a></li>
                <li><a href="{% url 'core:applygroup' %}">Apply Group</a></li>
            {% endif %}
            </ul>
        </div>

        <hr />

        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <br/>
        <hr />

        <div>
            If you have any question please contact sofiax.fernandez@estudiante.uam.es
        </div>

    </body>
</html>

PSI/psi_p4/labassign/templates/core/breakpair.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Break Pair
{% endblock %}

{% block body_block %}
	<form method="post" action="{% url 'core:breakpair' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" name="myPair">
	</form>
	{% if not error %}
		Could not process your request
	{% endif%}

{% endblock %}

PSI/psi_p4/labassign/templates/core/convalidation.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Convalidation
{% endblock %}

{% block body_block %}
        <h1>Convalidation Request Page</h1>
        You must have at least a <b>{{ otherConstrains.minGradeTheoryConv }} in theory</b> and a <b>{{ otherConstrains.minGradeLabConv }} in the lab </b> to convalidate your grades <br/>
	    {% if user.gradeTheoryLastYear >= otherConstrains.minGradeTheoryConv and user.gradeLabLastYear >= otherConstrains.minGradeLabConv %}
            {% if pairs1 or pairs2 %}
                You do not satify the requeriments for convalidation. You must leave your team partner before convalidating you grades<br>
            {% else %}
                Congratulations, your grades are theory=<b>{{ user.gradeTheoryLastYear }}</b> and lab=<b>{{ user.gradeLabLastYear }}</b>. You satisfy them.<br>
            {% endif %}
        {% else %}
			Your grades, <b>theory={{ user.gradeTheoryLastYear }}</b> and <b>lab={{ user.gradeLabLastYear }}</b> do not satify the requeriments for convalidation<br>
		{% endif %}
{% endblock %}

PSI/psi_p4/labassign/templates/core/home.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}

    {% if user.is_authenticated %}
        <p> Summary page for <b>{{ user.first_name }} {{ user.last_name }}</b>, (your theory group is {{ user.theoryGroup.groupName }} )</p>
        <h2>Convalidation</h2>
        {% if user.convalidationGranted == False %}
            Your lab assignments have NOT been or do not pass the requirements to be convalidated.<br/>
            (If you wish to request a convalidation press the "convalidation" button.)
        {% else %}
            Your lab assignments have been convalidated.
        {% endif%}

        <h2>Pair Status</h2>
        {% if pairs.student1.id == user.id or pairs2.student2.id == user.id  %}
            {% if pairs2.validated == False %}
                You have applied for a pair and your petition is being process.
            {% else %}
                {% if pairs.student1.id == user.id %}
                    You have applied for a pair and your partner is <b>{{ pairs.student2.first_name }} {{ pairs.student2.last_name }}</b>
                {% else %}
                    You have applied for a pair and your partner is <b>{{ pairs2.student1.first_name }} {{ pairs2.student1.last_name }}</b>
                {% endif %}
            {% endif %}
        {% else %}
            You have <b>NOT</b> applied for a pair
        {% endif%}

        <h2>Selected Group</h2>
        {% if user.labGroup != None %}
            Your laboratory group is: <b>{{ user.labGroup.groupName }}</b>
        {% else %}
            You have <b>NOT</b> selected a laboratory group
        {% endif%}
    {% else %}
		This web site allows EDAT students to select which laboratory group they wish to enroll in. Please follow the steps below<br/>
		<ol>
			<li>Login</li>
			<li>Apply for convalidation if appropriate</li>
			<li>Select partner</li>
			<li>Select group</li>
        </ol>
    {% endif %}

{% endblock %}

PSI/psi_p4/labassign/templates/core/login.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        Hi  <b>{{ user.first_name }} {{ user.last_name }}</b>, you are already logged in.<br/>
        Log out if you want to login as another user.
    {% else %}
        <h1>Please login</h1>
        <form id="login_form" method="post" action="{% url 'core:login' %}">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />
            <input type="submit" value="submit" />
        </form>
    {% endif %}
{% endblock %}